### ISSUE TITLE
github page 배포 시 firebase api key 사용 문제

### ISSUE THREAD

**Issue by NCookies** [NCookies/sparta-web-starter#1]
현재 로컬 개발 환경에서는 외부에 firebase API key를 노출시키지 않기 위해 관련 config 파일을 .gitignore에 등록해서 사용하고 있다.

`firebaseConfig.js`
```javascript
// Firebase 구성 정보 설정
// For Firebase JS SDK v7.20.0 and later, measurementId is optional
const firebaseConfig = {
    apiKey: "~~~",
    authDomain: "~~~",
    projectId: "~~~",
    storageBucket: "~~~",
    messagingSenderId: "~~~",
    appId: "~~~",
    measurementId: "~~~"
};
```

`index.html`
```html
...
<head>
    <script src="../config/firebaseConfig.js"></script>
...
```

이러한 config를 배포 환경에서도 동일하게 사용하기 위해 github workflow에서 secrets을 사용하려고 한다. 그러나 `index.html`에서 config 파일을 제대로 읽어들이지 못하고 있다.

`deploy.yml`
```yml
echo "const firebaseConfig = {
    apiKey: '${{ secrets.FIREBASE_API_KEY }}',
    authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
    projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
    storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
    messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
    appId: '${{ secrets.FIREBASE_APP_ID }}',
    measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
};" > config/firebaseConfig.js
```

```
index.html:79 Uncaught ReferenceError: firebaseConfig is not defined
    at index.html:79:35
```
